server:
  port: 8020
spring:
  application:
    name: coffee-power-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/chengshangqian/coffee-power.git  # 配置git仓库的地址
          search-paths: src/coffee-power-config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: username  # git仓库的账号
          password: password  # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"